version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: chat_db
    ports:
      - 27017:27017
    volumes:
      - ~/repos/go-practice/mongodb/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
